version: '2'
services:
  eurekaserver:
    image: priort/eurekaserver:v1
    ports:
      - "8761:8761"
  configserver:
    image: priort/configurationserver:v1
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_PORT: "8761"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka"
  zuulserver:
    image: priort/zuulserver:v1
    ports:
      - "5555:5555"
    environment:
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_PORT: "8888"
      CONFIGSERVER_URI: "http://configurationserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka"
      PROFILE: "default"
  kafkaserver:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
  organizationservice:
    image: priort/organizationservice:v1
    ports:
       - "8081:8081"
    environment:
      PROFILE: "aws-dev"
      SERVER_PORT: "8081"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      ZUULSERVER_PORT:     "5555"
      KAFKASERVER_PORT:    "2181"
      REDIS_PORT:          "6379"

  licensingservice:
    image: priort/licensingservice:v1
    ports:
      - "8080:8080"
    environment:
      PROFILE: "aws-dev"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      ZUULSERVER_PORT:     "5555"
      KAFKASERVER_PORT:    "2181"
      REDIS_PORT:          "6379"




