spring:
  cloud:
    stream:
      bindings:
        output:
          destination:  organizationChangeTopic
          content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    root: INFO
    com:
      eagleeye: DEBUG
